OpenDataology/metadata-api

Dockerfile, k8s/deployment.yaml, k8s/service.yaml
=> update k8s yaml file

src/main.go
update database connetion status
=> update database connetion status

.gitignore, README.md, k8s/configMap - template.yaml, k8s/deployment.yaml, src/config/config.go, src/config/config_template.yaml, src/database/connect.go, src/main.go
=> update config file to env

README.md
=> add structure png to readme

.gitignore, src/config/config.go
=> fix config error

README.md
=> add coc link

go.mod, go.sum, src/controllers/basic.go, src/controllers/datalicense.go, src/models/datalicense.go, src/models/datasets.go, src/services/datalicense.go, src/utils/pagination.go
=> add pagination

go.mod, src/models/datalicense.go, src/models/datasets.go, src/models/model.go, src/utils/pagination.go
=> fix base model

src/services/datalicense.go
=> fix return param

src/controllers/datalicense.go, src/models/datalicense.go, src/routes/router.go, src/services/datalicense.go
=> add GetLicenseDataById

src/models/datalicense.go
=> fix GetDatalicenseDataByID

src/controllers/basic.go, src/controllers/datalicense.go, src/controllers/dataset.go, src/models/datasets.go, src/routes/router.go, src/services/datalicense.go
=> add ListDatasets

src/routes/router.go, src/services/dataset.go
=> add dataset query functions

src/models/datasets.go
=> fix get_dataset_by_id

src/controllers/datalicense.go, src/models/datalicense.go, src/services/datalicense.go
Add type filter to GetDatalicensesByPage
=> Add type filter to GetDatalicensesByPage

src/controllers/datalicense.go
=> optimize ListDatasetLicenses

src/controllers/datalicense.go, src/controllers/dataset.go, src/models/datalicense.go, src/models/datasets.go, src/routes/router.go, src/services/datalicense.go, src/services/dataset.go
=> update license and searching

src/models/datalicense.go, src/models/datasets.go
=> fix license searching

src/controllers/datalicense.go, src/models/datalicense.go, src/services/datalicense.go
update searching by license types
=> update searching by license types

src/controllers/datalicense.go, src/controllers/dataset.go, src/models/datalicense.go, src/models/datasets.go, src/routes/router.go, src/services/datalicense.go, src/services/dataset.go
update dataset and license index
=> update dataset and license index

src/controllers/datalicense.go
=> fix license_type

k8s/deployment.yaml
=> update yaml version

src/controllers/user.go
=> fix user sign up

k8s/deployment.yaml, src/controllers/user.go, src/models/user.go, src/services/user.go
=> fix sign up issue

k8s/deployment.yaml, src/routes/router.go
=> fix request type

src/controllers/user.go
=> fix post param

k8s/deployment.yaml, src/models/datalicense.go
Signed-off-by: Clement Li <robekeane@126.com>
=> Update insert new license

k8s/deployment.yaml, src/services/datalicense.go
Signed-off-by: Clement Li <robekeane@126.com>
=> fix set_license error

k8s/deployment.yaml, src/models/datalicense.go
Signed-off-by: Clement Li <robekeane@126.com>
=> fix validity_period

k8s/deployment.yaml
Signed-off-by: Clement Li <robekeane@126.com>
=> fix condition of json input

src/config/config.go, src/controllers/basic.go, src/controllers/datalicense.go, src/controllers/dataset.go, src/controllers/user.go, src/database/connect.go, src/main.go, src/models/datalicense.go, src/models/datasets.go, src/models/model.go, src/models/user.go, src/routes/middleware.go, src/routes/router.go, src/services/datalicense.go, src/services/dataset.go, src/services/user.go, src/utils/pagination.go, src/utils/token.go
Signed-off-by: san5167 <1355969973@qq.com>
=> add license describe for code file
